apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xdmod-reader-query-namespaces
subjects:
- kind: ServiceAccount
  name: xdmod-reader
  namespace: xdmod-tzumainn
roleRef:
  kind: ClusterRole
  name: query-namespaces
  apiGroup: rbac.authorization.k8s.io
